name: http_structure
description: Conventions of Datasource Management
version: 0.0.1
publish_to: "none"

environment:
  sdk: ">=3.0.1 <4.0.0"
  flutter: ">=3.19.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.1
  universal_io: ^2.2.2
  module_structure:
    git:
      url: git@github.com:coolosos/module_structure.git
      path: module_structure
      ref: main

dev_dependencies:
  flutter_test:
    sdk: flutter
  coolint: 2.0.0

flutter:
  generate: true
